version: 0.2
phases: 

  prebuild:
    commands:
      -npm install

  build:
    # made from jenkins
    commands:
      - npm ci
      - npm run build
      #aws s3 sync ./build s3://javawockeez-capstone-project3-react
artifacts:
  files:
    #Dockerfile
    - '**/*'
    #nginx/nginx.conf
   discard-paths: no
   base-directory: 'build'
 
    
  
